/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fxConverter;

public class App {

    public static void main(String[] args) {

        Converter Converter = new Converter();

        Converter.runConverter();
    }
}