/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_04_Wed_16_Frank_Group;

public class App {

    public static void main(String[] args) {

        Convertor convertor = new Convertor();

        convertor.runConvertor();
    }
}